server:
  port: 8081




# Mysql８以上の場合、urlの設定には下記属性設定する必要
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/emailsending?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true
    username: root
    password: uid007163
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    hiddenmethod-filter-enabled: true

mybatis:
  mapper-locations: classpath:resources/mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true



